version: "3.7"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - /mnt/media:/media
      - jellyfin_config:/config
      - jellyfin_cache:/cache
    restart: unless-stopped
    environment:
      - JELLYFIN_Preset=ultrafast
      - JELLYFIN_CRF=30
      - JELLYFIN_Threads=2

volumes:
  jellyfin_config:
  jellyfin_cache:
